name: DarkHorse
description: DarkHorse is a Bukkit plugin designed to let you spawn in all types of horses.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/darkhorse/
main: com.justinwflory.darkhorse.DarkHorse
version: 1.3

commands:
   dh:
      description: Spawn a horse.
      usage: /dh <horse, donkey, mule, skeleton, zombie> [tamed] [chest]
      aliases: [darkhorse, horse]

permissions:
    darkhorse.*:
        description: Gives access to all DarkHorse commands.
        children:
            darkhorse.horse: true
            darkhorse.donkey: true
            darkhorse.mule: true
            darkhorse.skeleton: true
            darkhorse.zombie: true
        default: op
    darkhorse.horse:
        description: Spawn all normal horses.
        default: op
    darkhorse.donkey:
        description: Spawn all donkeys.
        default: op
    darkhorse.mule:
        description: Spawn all mules.
        default: op
    darkhorse.skeleton:
        description: Spawn all skeleton horses.
        default: op
    darkhorse.zombie:
        description: Spawn all zombie horses.
        default: op