name: DarkHorse
description: DarkHorse is a Bukkit plugin designed to let you spawn in all types of horses.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/darkhorse/
main: co.j_f.darkhorse.DarkHorse
version: 1.2.2

commands:
   dh:
      description: Spawn a horse.
      usage: /dh <horse, donkey, mule, skeleton, zombie> [tamed]
      aliases: [darkhorse, horse]

permissions:
    darkhorse.*:
        description: Gives access to all DarkHorse commands.
        children:
            darkhorse.horse: true
            darkhorse.horse.tamed: true
            darkhorse.donkey: true
            darkhorse.donkey.tamed: true
            darkhorse.mule: true
            darkhorse.mule.tamed: true
            darkhorse.skeleton: true
            darkhorse.skeleton.tamed: true
            darkhorse.zombie: true
            darkhorse.zombie.tamed: true
        default: op
    darkhorse.horse:
        description: Spawn a normal horse.
        default: op
    darkhorse.horse.tamed:
        description: Spawn a tamed normal horse.
        default: op
    darkhorse.donkey:
        description: Spawn a donkey.
        default: op
    darkhorse.donkey.tamed:
        description: Spawn a tamed donkey.
        default: op
    darkhorse.mule:
        description: Spawn a mule.
        default: op
    darkhorse.mule.tamed:
        description: Spawn a tamed mule.
        default: op
    darkhorse.skeleton:
        description: Spawn a skeleton horse.
        default: op
    darkhorse.skeleton.tamed:
        description: Spawn a tamed skeleton horse.
        default: op
    darkhorse.zombie:
        description: Spawn a zombie horse.
        default: op
    darkhorse.zombie.tamed:
        description: Spawn a tamed zombie horse.
        default: op