name: DarkHorse
description: DarkHorse is a Bukkit plugin designed to let you spawn in all types of horses.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/darkhorse/
main: com.crystalcraftmc.darkhorse.Main
version: 1.1

commands:
   horse1:
      description: Spawn a normal horse.
      usage: /horse1
      aliases: [normalhorse, horsenormal, spawnhorse1, sh1]
      permission: darkhorse.normal
      permission-message: You don't have <permission>
   horse2:
      description: Spawn a donkey.
      usage: /horse2
      aliases: [donkey, spawndonkey, spawnhorse2, sh2]
      permission: darkhorse.donkey
      permission-message: You don't have <permission>
   horse3:
      description: Spawn a skeleton horse.
      usage: /horse3
      aliases: [skeletonhorse, horseskeleton, spawnhorse3, sh3]
      permission: darkhorse.skeleton
      permission-message: You don't have <permission>
   horse4:
      description: Spawn a zombie horse.
      usage: /horse4
      aliases: [zombiehorse, horsezombie, spawnhorse4, sh4]
      permission: darkhorse.zombie
      permission-message: You don't have <permission>

permissions:
    darkhorse.*:
        description: Gives access to all DarkHorse commands.
        children:
            darkhorse.normal: true
            darkhorse.donkey: true
            darkhorse.skeleton: true
            darkhorse.zombie: true
    darkhorse.normal:
        description: Spawn a normal horse.
        default: op
    darkhorse.donkey:
        description: Spawn a donkey.
        default: op
    darkhorse.skeleton:
        description: Spawn a skeleton horse.
        default: op
    darkhorse.zombie:
        description: Spawn a zombie horse.
        default: op